# Generated by Django 4.2.30 on 2026-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webcomic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English'), ('indonesian', 'Indonesian'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese')], max_length=20)),
                ('ep_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['language', 'ep_number'],
                'unique_together': {('language', 'ep_number')},
            },
        ),
    ]
