# Generated by Django 4.2.30 on 2026-08-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcomic',
            name='ep_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='comicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comics/pages/')),
                ('page_num', models.PositiveIntegerField(default=1)),
                ('webcomic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='comics_app.webcomic')),
            ],
            options={
                'ordering': ['webcomic', 'page_num'],
                'unique_together': {('webcomic', 'page_num')},
            },
        ),
    ]
