# Generated by Django 6.1 on 2026-08-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_app', '0002_alter_webcomic_ep_number_comicpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcomic',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('indonesian', 'Indonesian'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('chinese', 'Chinese')], max_length=20),
        ),
    ]
