# Generated by Django 6.1 on 2026-08-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_app', '0003_alter_webcomic_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcomic',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('indonesian', 'Indonesian'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('chinese', 'Chinese'), ('italian', 'Italian'), ('filipino', 'Filipino')], max_length=20),
        ),
    ]
