# Generated by Django 6.1.1 on 2026-09-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_app', '0005_alter_webcomic_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcomic',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('indonesian', 'Indonesian'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('chinese', 'Chinese'), ('italiano', 'Italiano'), ('filipino', 'Filipino'), ('ukranian', 'Ukranian')], max_length=20),
        ),
    ]
