<<<<<<< HEAD
# Generated by Django 6.1.1 on 2026-09-08 13:48
=======
# Generated by Django 6.1.1 on 2026-09-24 08:28
>>>>>>> d3ee7bff9069228ecb066363524e86de992b471a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_app', '0006_alter_webcomic_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcomic',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('indonesian', 'Indonesian'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('chinese', 'Chinese'), ('italiano', 'Italiano'), ('filipino', 'Filipino'), ('ukrainian', 'Ukrainian')], max_length=20),
        ),
    ]
