from django.shortcuts import render, get_object_or_404
from .models import webcomic

TRANSLATIONS = {
    "english": {
        "comics_title": "COMICS",
        "main_part": "here, you can read the webcomic! (for free!)",
        "community": "COMMUNITY",
        "discord": "Discord Server!",
        "patreon": "Patreon Profile!",
        "merch": "Merch Website!",
        "twitter": "Twitter/X Profile!",
        "wiki": "Official Wiki!",
        "youtube": "Youtube Channel!",
        "button": "View the webcomic here!",
        "episode": "Episode",
        "ep_1": "DEUS EX MACHINA",
        "ep_2": "THIS WAS THE LAST PLACE MY FATHER WAS SEEN",
        "ep_3": "YOU ONCE LEFT ME WITH THIS",
        "ep_4": "FIGHT OVER",
        "ep_5": "HERE, I'LL TEACH YOU HOW TO COOK",
        "ep_6": "ANYTIME, WHENEVER",
        "ep_7": "CAME HOME TO SEE THE BAD NEWS",
        "ep_8": "DON'T GO",
        "ep_9": "THE BEAUTIFUL SILENCE AFTER THE BANG",
        "owned_by": "maumakanapa is owned by:",
        "assets": (
            "every asset used belongs to <br> labirhin and it's respective"
            " creators"
        ),
        "made_with": "website made with love by:",
        "selector": "/english/comics",
        "index": "/english/",
        "about": "/english/about",
        "about1": "this website was made with the sole purpose of <br> being a 'backup' in case other websites that <br> host Mau Makan Apa randomly go down",
        "about2": "a lot of hard work was put onto this, so i hope that <br> you, the reader, actually enjoys it, <br> as much as i enjoyed making the website it self!",
        "about3": "more stuff will get added here in the future, such as: <br> more languages, more stuff about MMA, and much more!",
        "about4": "thank you to everyone who motivated me to actually <br> make this website!",
        "about5": "-laurah",
        "abouth1": "about this website!",
        "notcomic1": "episode not available...",
        "notcomic2": "what typa episode are you trying to access????",
        "notcomic3": "back to the webcomics",
        "aboutme": "about me!",
        "aboutme1": "my name is laurah, i'm the person who made <br> this website, and i'm just your typical web developer!",
        "aboutme2": "i'm also a youtuber, so if you want to go <br> check out my channel, you can do so here: ",
        "aboutme3": "fun fact: this website is actually open-sourced <br> on github! you can go check it out here:  ",
        "aboutme4": "thank you!!!",
        "languages": "view more languages here!",
    },
    "indonesian": {
        "main_part": "di sini, kamu bisa membaca webcomic-nya! (gratis!)",
        "community": "MASYARAKAT",
        "comics_title": "KOMIK",
        "discord": "Server Discord",
        "patreon": "Profil Patreon",
        "merch": "Situs Web Merch",
        "twitter": "Profil Twitter/X",
        "wiki": "Wiki Resmi!",
        "youtube": "Saluran Youtube!",
        "button": "Lihat webkomik di sini!",
        "episode": "Episode",
        "ep_1": "DEUS EX MACHINA",
        "ep_2": "INILAH TEMPAT TERAKHIR AYAHKU TERLIHAT",
        "ep_3": "KAMU JUGA PERNAH NITIPIN AKU INI",
        "ep_4": "FIGHT OVER",
        "ep_5": "SINI AKU AJARIN KAMU MASAK",
        "ep_6": "KAPAN KAPAN ITU BISA KAPAN AJA",
        "ep_7": "PULANG UNTUK MENYAKSIKAN KABAR BURUK",
        "ep_8": "JANGANLAH KAU PERGI",
        "ep_9": "KESUNYIAN YANG INDAH SETELAH KERIBUTAN",
        "owned_by": "maumakanapa dimiliki oleh:",
        "assets": (
            "setiap aset yang digunakan adalah milik <br> labirhin dan"
            " pencipta masing-masing"
        ),
        "made_with": "situs web dibuat dengan cinta oleh:",
        "selector": "/indonesian/comics",
        "index": "/indonesian/",
        "about": "/indonesian/about",
        "about1": "situs web ini dibuat dengan tujuan semata-mata untuk <br>menjadi 'cadangan' jika situs web lain yang <br>menghosting Mau Makan Apa tiba-tiba tidak aktif.",
        "about2": "banyak kerja keras yang dicurahkan untuk ini, jadi saya harap <br>Anda, pembaca, benar-benar menikmatinya, <br>sama seperti saya menikmati pembuatan situs web itu sendiri!",
        "about3": "lebih banyak hal akan ditambahkan di sini di masa mendatang, seperti: <br>lebih banyak bahasa, lebih banyak hal tentang MMA, dan <br>masih banyak lagi!",
        "about4": "terima kasih kepada semua orang yang memotivasi saya untuk <br>benar-benar membuat situs web ini!",
        "about5": "-laurah",
        "abouth1": "tentang situs web ini!",
        "notcomic1": "episode tidak tersedia...",
        "notcomic2": "jenis episode apa yang coba kamu akses????",
        "notcomic3": "kembali ke webcomic",
        "aboutme": "tentang saya!",
        "aboutme1": "nama saya laurah, akulah orang yang membuat <br> situs web ini, dan aku hanyalah pengembang web biasa!",
        "aboutme2": "aku juga seorang youtuber, jadi jika kamu ingin <br> memeriksa saluranku, kamu bisa melakukannya di sini: ",
        "aboutme3": "fakta menarik: situs web ini sebenarnya bersumber terbuka <br> di github! kamu bisa memeriksanya di sini:",
        "aboutme4": "terima kasih!!!",
        "languages": "lihat bahasa lainnya di sini!",
    },
    "spanish": {
        "comics_title": "COMICS",
        "main_part": "¡aquí puedes leer el webcómic! (¡gratis!)",
        "community": "COMUNIDAD",
        "discord": "Servidor de Discord",
        "patreon": "Perfil de Patreon",
        "merch": "Sitio Web de Merch",
        "twitter": "Perfil de Twitter/X",
        "wiki": "¡Wiki Oficial!",
        "youtube": "¡Canal de Youtube!",
        "button": "¡Mira la webcomic aquí!",
        "episode": "Episodio",
        "ep_1": "DEUS EX MACHINA",
        "ep_2": "ESTE ES EL ULTIMO LUGAR DONDE MI PADRE FUE VISTO",
        "ep_3": "UNA VEZ ME DEJASTE CON ESTO",
        "ep_4": "FIGHT OVER",
        "ep_5": "MIRA, TE ENSEÑARE COMO COCINAR",
        "ep_6": "CUANDO Y COMO SEA",
        "ep_7": "LLEGUE A CASA PARA VER MALAS NOTICIAS",
        "ep_8": "NO TE VAYAS",
        "ep_9": "EL HERMOSO SILENCIO DESPUÉS DE LA EXPLOSIÓN",
        "owned_by": "maumakanapa es propiedad de:",
        "assets": (
            "todos los recursos utilizados pertenecen a <br> labirhin y a sus"
            " respectivos creadores"
        ),
        "made_with": "sitio web hecho con amor por:",
        "selector": "/spanish/comics",
        "index": "/spanish/",
        "about": "/spanish/about",
        "about1": "este sitio web fue hecho con el único propósito de <br>ser una 'copia de seguridad' en caso de que otros sitios web que <br>alojan Mau Makan Apa se caigan repentinamente.",
        "about2": "¡se puso mucho esfuerzo en esto, así que espero que <br>tú, el lector, realmente lo disfrutes, <br>tanto como yo disfruté haciendo el sitio web en sí!",
        "about3": "se agregarán más cosas aquí en el futuro, como: <br>más idiomas, más cosas sobre MMA y <br>mucho más!",
        "about4": "¡gracias a todos los que me motivaron a <br>hacer este sitio web!",
        "about5": "-laurah",
        "abouth1": "acerca de este sitio web!",
        "notcomic1": "episodio no disponible...",
        "notcomic2": "¿¿¿¿a qué tipo de episodio intentas acceder????",
        "notcomic3": "volver a los webcómics",
        "aboutme": "¡sobre mí!",
        "aboutme1": "¡mi nombre es laurah, soy la persona que hizo <br> este sitio web y soy una desarrolladora web típica!",
        "aboutme2": "también soy youtuber, así que si quieres <br> visitar mi canal, puedes hacerlo aquí: ",
        "aboutme3": "dato curioso: ¡este sitio web es de código abierto <br> en github! puedes consultarlo aquí:",
        "aboutme4": "¡¡¡muchas gracias!!!",
        "languages": "ver más idiomas aqui!",
    },
    "portuguese": {
        "comics_title": "QUADRINHOS",
        "main_part": "aqui você pode ler a webcomic! (de graça!)",
        "community": "COMUNIDADE",
        "discord": "Servidor do Discord!",
        "patreon": "Perfil do Patreon!",
        "merch": "Site de Merch!",
        "twitter": "Perfil do Twitter/X",
        "wiki": "Wiki Oficial!",
        "youtube": "Canal do Youtube!",
        "button": "Veja a webcomic aqui!",
        "episode": "Episódio",
        "ep_1": "DEUS EX MACHINA",
        "ep_2": "O ÚLTIMO LUGAR ONDE VIRAM O MEU PAI",
        "ep_3": "FOI ISTO O QUE VOCÊ ME DEIXOU",
        "ep_4": "ULTIMATO",
        "ep_5": "VEM CÁ, VOU TE ENSINAR A COZINHAR",
        "ep_6": "A QUALQUER HORA, EM QUALQUER LUGAR",
        "ep_7": "FINALMENTE EM CASA PARA VER AS MÁS NOTÍCIAS",
        "ep_8": "POR FAVOR, NÃO VÁ!",
        "ep_9": "A CALMARIIA DEPOIS DA TEMPESTADE",
        "owned_by": "maumakanapa pertence a:",
        "assets": (
            "todos os recursos usados pertencem a <br> labirhin e aos seus"
            " respectivos criadores"
        ),
        "made_with": "site feito com amor por:",
        "selector": "/portuguese/comics",
        "index": "/portuguese/",
        "about": "/portuguese/about",
        "about1": "este site foi feito com o objetivo de <br>ser um backup em caso que os sites que <br>tem o comic Mau Makan Apa vão a baixo.",
        "about2": "eu trabalhei muito neste site, então eu espero que <br>tu, o leitor(a), goste do site, como eu gostei de o fazer.",
        "about3": "eu planeio em adicionar mais coisas no futuro, como: <br>mais línguas, mais coisas sobre MMA, e muito mais!",
        "about4": "obrigada a todos por terem me motivado <br>a fazer este site!",
        "about5": "-laurah (sim, sou portuguesa, não brasileira c:)",
        "abouth1": "sobre o site!",
        "notcomic1": "página indisponível..",
        "notcomic2": "que tipo de página é que estás a tentar aceder????",
        "notcomic3": "voltar para a webcomic",
        "aboutme": "sobre mim!",
        "aboutme1": "o meu nome é laurah, eu sou a pessoa que fez <br> este site, e sou a tua típica programadora de Web",
        "aboutme2": "eu também sou uma youtuber, então se quiseres ir dar <br> uma olhada, podes ir ver aqui: ",
        "aboutme3": "fun fact: este site é de código aberto <br> no github! tu podes ir ver aqui: ",
        "aboutme4": "obrigada!!!!!!!",
        "languages": "veja mais idiomas aqui!",
    },
    "russian": {
        "comics_title": "КОМИКСЫ",
        "main_part": "здесь вы можете почитать веб-комикс! (бесплатно!)",
        "community": "СООБЩЕСТВО",
        "discord": "Сервер Discord!",
        "patreon": "Профиль Patreon!",
        "merch": "Сайт с мерчем!",
        "twitter": "Профиль Twitter/X!",
        "wiki": "Официальная Вики!",
        "youtube": "Ютуб Канал!",
        "button": "Смотреть веб-комикс здесь!",
        "episode": "Эпизод",
        "ep_1": "Деус Экс Макина",
        "ep_2": "Где-то Там В Последний Раз Видели Моего Отца",
        "ep_3": "Ты Мне Тогда Вручил Это",
        "ep_4": "Конфликт",
        "ep_5": "Давай, Я Научу Тебя Готовить",
        "ep_6": "Навсегда, Никогда",
        "ep_7": "Как Бы Ты Не Старался",
        "ep_8": "Отпусти",
        "ep_9": "Долгожданная Тишина",
        "owned_by": "владелец maumakanapa:",
        "assets": "все использованные материалы принадлежат <br> labirhin и их соответствующим создателям",
        "made_with": "сайт создан с любовью:",
        "selector": "/russian/comics",
        "index": "/russian/",
        "about": "/russian/about",
        "about1": "этот сайт был создан с единственной целью <br> быть 'резервной копией' на случай, если другие сайты, <br> где размещен Mau Makan Apa, внезапно перестанут работать",
        "about2": "в это было вложено много труда, поэтому я надеюсь, что <br> вам, читатель, это действительно понравится <br> так же сильно, как мне понравилось создавать сам сайт!",
        "about3": "в будущем сюда добавится больше нового, например: <br> больше языков, больше материалов о MMA и многое другое!",
        "about4": "спасибо всем, кто мотивировал меня <br> сделать этот сайт!",
        "about5": "-лора",
        "abouth1": "об этом сайте!",
        "notcomic1": "эпизод недоступен...",
        "notcomic2": "что за эпизод вы пытаетесь открыть????",
        "notcomic3": "вернуться к веб-комиксам",
        "aboutme": "о обо мне!",
        "aboutme1": "моё имя лора, я тот человек, который создал <br> этот сайт, и я просто типичный веб-разработчик!",
        "aboutme2": "я также ютубер, так что если вы хотите <br> заглянуть на мой канал, вы можете сделать это здесь:",
        "aboutme3": "интересный факт: этот сайт на самом деле с открытым исходным кодом <br> на github! вы можете посмотреть его здесь:",
        "aboutme4": "спасибо вам!!!",
        "languages": "посмотреть другие языки здесь!",
    },
    "chinese": {
        "comics_title": "漫画",
        "main_part": "在这里，你可以阅读网络漫画！（免费！）",
        "community": "社群",
        "discord": "Discord 服务器！",
        "patreon": "Patreon 主页！",
        "merch": "周边网站！",
        "twitter": "Twitter/X 主页！",
        "wiki": "官方Wiki!",
        "youtube": "Youtube频道!",
        "button": "在此处查看网络漫画!",
        "episode": "话",
        "ep_1": "机械降神的驾驶员",
        "ep_2": "这是我父亲最后被见到的地方",
        "ep_3": "曾与之物",
        "ep_4": "决斗争胜",
        "ep_5": "来，我教你做饭",
        "ep_6": "时空不定",
        "ep_7": "归家见噩耗",
        "ep_8": "不要离去",
        "ep_9": "爆炸之后，万籁俱静",
        "owned_by": "maumakanapa 归属于：",
        "assets": "使用所有素材均属于 <br> labirhin 及其各自的创作者",
        "made_with": "网站由以下人员倾心制作：",
        "selector": "/chinese/comics",
        "index": "/chinese/",
        "about": "/chinese/about",
        "about1": "创建本网站的唯一目的就是 <br> 作为“备份”，以防托管 Mau Makan Apa 的其他网站 <br> 随机瘫痪",
        "about2": "这其中倾注了许多心血，所以我希望 <br> 作为读者的你能够真正喜欢它， <br> 就像我享受制作这个网站的过程一样!",
        "about3": "未来这里还会添加更多内容，例如： <br> 更多语言、更多关于 MMA 的内容等等!",
        "about4": "感谢所有激励我 <br> 制作这个网站的人!",
        "about5": "-laurah",
        "abouth1": "关于本网站!",
        "notcomic1": "章节不可用...",
        "notcomic2": "你到底在尝试访问什么类型的章节????",
        "notcomic3": "返回网络漫画",
        "aboutme": "关于我!",
        "aboutme1": "我叫拉拉（laurah），我是制作 <br> 这个网站的人，我只是一个普通的网页开发者!",
        "aboutme2": "我同时也是一名油管（YouTube）博主，如果你想去 <br> 看看我的频道，可以在这里找到：",
        "aboutme3": "趣事：这个网站其实在 <br> GitHub上是开源的! 你可以在这里查看：",
        "aboutme4": "非常感谢！！！",
        "languages": "在此查看更多语言!",
    },
    "filipino": {
        "comics_title": "MGA KOMIKS",
        "main_part": "dito, maaari kang magbasa ng webcomic! (nang libre!)",
        "community": "KOMUNIDAD",
        "discord": "Discord Server!",
        "patreon": "Patreon Profile!",
        "merch": "Merch Website!",
        "twitter": "Twitter/X Profile!",
        "wiki": "Opisyal na Wiki!",
        "youtube": "Channel sa Youtube!",
        "button": "Tingnan ang webcomic dito!",
        "episode": "Episode",
        "ep_1": "DEUS EX MACHINA",
        "ep_2": "ITO ANG HULING LUGAR KUNG SAAN NAKITA ANG AKING AMA",
        "ep_3": "MINSAN MO AKONG INIWAN NG NITO",
        "ep_4": "TAPOS NA ANG LABAN",
        "ep_5": "HALIKA, ITUTURO KO SA IYONG MAGLUTO",
        "ep_6": "KAILANMAN, ANUMANG ORAS",
        "ep_7": "UMUWI PARA MAKITA ANG MASAMANG BALITA",
        "ep_8": "HUWAG KANG UMALIS",
        "ep_9": "ANG MAGANDANG TAHIMIK PAGKATAPOS NG PUTOK",
        "owned_by": "ang maumakanapa ay pagmamay-ari ni:",
        "assets": "ang bawat asset na ginamit ay pagmamay-ari ng <br> labirhin at ng kani-kanilang mga creator",
        "made_with": "ang website na ito ay ginawa nang may pagmamahal ni:",
        "selector": "/filipino/comics",
        "index": "/filipino/",
        "about": "/filipino/about",
        "about1": "ang website na ito ay ginawa para sa tanging layunin na <br> maging 'backup' kung sakaling biglang bumagsak ang ibang mga website <br> na nagho-host ng Mau Makan Apa",
        "about2": "maraming hirap ang ibinuhos dito, kaya umaasa ako na <br> ikaw, ang mambabasa, ay talagang mag-enjoy dito, <br> tulad ng pag-enjoy ko sa paggawa ng website mismo!",
        "about3": "mas maraming bagay ang idadagdag dito sa hinaharap, tulad ng: <br> mas maraming wika, mas maraming bagay tungkol sa MMA, at marami pang iba!",
        "about4": "salamat sa lahat ng nag-udyok sa akin na <br> gawin talaga ang website na ito!",
        "about5": "-laurah",
        "abouth1": "tungkol sa website na ito!",
        "notcomic1": "hindi available ang episode...",
        "notcomic2": "anong klaseng episode ba ang sinusubukan mong puntahan????",
        "notcomic3": "bumalik sa mga webcomic",
        "aboutme": "tungkol sa akin!",
        "aboutme1": "ang pangalan ko ay laurah, ako ang gumawa <br> ng website na ito, at isa lang akong tipikal na web developer!",
        "aboutme2": "isa rin akong youtuber, kaya kung gusto mong <br> bisitahin ang aking channel, maaari mo itong gawin dito:",
        "aboutme3": "fun fact: ang website na ito ay open-source <br> sa github! maaari mo itong tignan dito: ",
        "aboutme4": "maraming salamat!!!",
        "languages": "tingnan ang iba pang mga wika dito!",
    },
    "italiano": {
        "comics_title": "FUMETTI",
        "main_part": "qui puoi leggere il webcomic! (gratuitamente!)",
        "community": "COMMUNITY",
        "discord": "Server Discord!",
        "patreon": "Profilo Patreon!",
        "merch": "Sito di Merch!",
        "twitter": "Profilo Twitter/X!",
        "wiki": "Wiki Ufficiale!",
        "youtube": "Canale Youtube!",
        "button": "Guarda il webcomic qui!",
        "episode": "Episodio",
        "ep_1": "DEUS EX MACHINA",
        "ep_2": "L'ULTIMO POSTO OVE FU VISTO MIO PADRE",
        "ep_3": "MI LASCIASTI CON QUESTO",
        "ep_4": "FIGHT OVER",
        "ep_5": "VIENI, TI INSEGNO A CUCINARE",
        "ep_6": "OGNIDDOVE, OGNIQUANDO",
        "ep_7": "ARRIVAI A CASA, ALLA BRUTTA NOTIZIA",
        "ep_8": "NON ANDARE",
        "ep_9": "LO STUPENDO SILENZIO DOPO L'ESPLOSIONE",
        "owned_by": "maumakanapa è di proprietà di:",
        "assets": "ogni risorsa utilizzata appartiene a <br> labirhin e ai rispettivi creatori",
        "made_with": "sito web realizzato con amore da:",
        "selector": "/italiano/comics",
        "index": "/italiano/",
        "about": "/italiano/about",
        "about1": "questo sito web è stato realizzato con l'unico scopo di <br> essere un 'backup' nel caso in cui altri siti web che <br> ospitano Mau Makan Apa dovessero smettere di funzionare",
        "about2": "ci è stato messo molto impegno, quindi spero che <br> tu, lettore, possa davvero apprezzarlo, <br> tanto quanto mi è piaciuto creare il sito stesso!",
        "about3": "altre cose verranno aggiunte qui in futuro, come ad esempio: <br> più lingue, più contenuti su MMA e molto altro!",
        "about4": "grazie a tutti coloro che mi hanno motivato a <br> fare davvero questo sito web!",
        "about5": "-laurah",
        "abouth1": "informazioni su questo sito!",
        "notcomic1": "episodio non disponibile...",
        "notcomic2": "che tipo di episodio stai cercando di raggiungere????",
        "notcomic3": "torna ai webcomic",
        "aboutme": "su di me!",
        "aboutme1": "mi chiamo laurah, sono la persona che ha creato <br> questo sito web e sono una normale sviluppatrice web!",
        "aboutme2": "sono anche una youtuber, quindi se vuoi <br> dare un'occhiata al mio canale, puoi farlo qui",
        "aboutme3": "curiosità: questo sito web è open-source <br> su github! puoi darci un'occhiata qui: ",
        "aboutme4": "grazie mille!!!",
        "languages": "visualizza altre lingue qui!",
    }
}

def index(request, lang="english"):
  if lang not in TRANSLATIONS:
    lang = "english"

  context = {
      "current_lang": lang,
      "t": TRANSLATIONS[lang],
  }
  return render(request, "comics_app/index.html", context)


def comic_list(request, lang):
  if lang not in TRANSLATIONS:
    lang = "english"

  context = {
      "current_lang": lang,
      "t": TRANSLATIONS[lang],
  }
  return render(request, "comics_app/select.html", context)

def page(request, lang, number):
    if lang not in TRANSLATIONS:
        lang = "english"

    comic = webcomic.objects.filter(language__iexact=lang, ep_number=number).first()

    if comic:
        pages = comic.pages.all()
        
        prev_comic = webcomic.objects.filter(
            language=comic.language,
            ep_number__lt=comic.ep_number
        ).order_by('-ep_number').first()
        next_comic = webcomic.objects.filter(
                language=comic.language,
                ep_number__gt=comic.ep_number
            ).order_by('ep_number').first()
    else:
        pages = []
        prev_comic = None
        next_comic = None
    
    context = {
            "current_lang": lang,
            "t": TRANSLATIONS[lang],
            "comic": comic,
            "pages": pages,
            "prev_comic": prev_comic,
            "next_comic": next_comic,
          }
    
    return render(request, "comics_app/comic.html", context)

def about(request, lang):
    if lang not in TRANSLATIONS:
        lang = "english"

    custom_fonts = {
       "russian": "russianlabi, sans-serif",
    }

    fonts = custom_fonts.get(lang, "Labirhin, sans-serif")

    context = {
        "current_lang": lang,
        "t": TRANSLATIONS[lang],
        "fonts": fonts,
    }

    return render(request, "comics_app/about.html", context)